feat(settings): tabs scrolls to top if navigated
whyboris/Video-Hub-App pull request #700
Opened 2021-09-13 05:05 UTC by dVp007

solving! Scroll to top when switching settings tabs #681

2021-09-13 13:11 UTC, whyboris commented
Thank you very much! The code looks like it will work 💯 -- I just want to test it out before merging 🤝

2021-09-14 23:29 UTC, whyboris commented on src/app/components/settings/settings.component.ts
> +    document.getElementById('settings').scrollTop = 0;
I added `console.log()` above this and can confirm that this method gets called every time you switch between the _Tabs_ in _Settings_, but it doesn't seem to actually scroll to the top 😕 

ps, when you add `ngOnChanges()` method to an Angular class, you should also add it to the class declaration:
```ts
export class SettingsComponent implements OnInit, OnChanges {
```

2021-09-14 23:36 UTC, whyboris requested changes
Unfortunately with your changes, the app does not scroll to the top of the tab when switching tabs.

I wonder if this will be useful: https://stackoverflow.com/a/46348211/5017391
`.scrollIntoView()`

I tried using it with your code but it still didn't work. I'm unsure what is going wrong. Please let me know if you'd like help with this 🤝

2021-09-19 17:38 UTC, dVp007 commented
Okay will check it before can you send me a video or a GIF so that I can figure out what is wrong. Because when I tried it was scrolled at the top.

2021-09-21 18:48 UTC, whyboris commented
To replicate:
<img width="400" alt="1" src="https://user-images.githubusercontent.com/17264277/134229582-fc7cb130-4155-435e-8c79-7dcad63206eb.png">
scroll down to bottom, now click on the 1st tab:
<img width="400" alt="2" src="https://user-images.githubusercontent.com/17264277/134229628-f1de08f1-bbe4-4f32-8312-4e9d6411e653.png">
notice the scrollbar is not at the top.
On your branch the scrollbar seems to move up a bit, but not to the top of the tab

2021-09-23 14:16 UTC, dVp007 commented
Can you please check i actually forgot to commit changes of a file. I guess it should work now.

2023-03-30 02:04 UTC, closed without merging