Herty/start with filter
whyboris/Video-Hub-App pull request #832
Opened 2023-10-24 09:45 UTC by Herty94

Resolves #617 

But there is need to connect now static strings to translation library.

2023-10-24 10:55 UTC, whyboris requested changes
Would you be able to undo the automated formatting / styling changes somehow?

All the `'` -> `"` changes as well as the others that auto-happened?

2023-11-05 23:16 UTC, Herty94 commented
Sorry for taking me so long. I hope I fixed all of the formatting changes. And I've added translation.

2023-11-09 20:48 UTC, whyboris commented
Hey @Herty94 - thank you for this clean PR contribution 🙇 ❤️ 
I'm eager to get back to VHA development in the coming months (still working on rebuilding my kitchen in the house). This PR will be merged in before the next release 👍 😁 👍 
I'll test it out locally before merging; if there's any small thing to adjust I'll do it after the merge -- looking at the code without running seems like it's 💯 ready 🚀 
Great work - thank you 😄

2026-06-18 21:11 UTC, whyboris commented
Thank you @Herty94 for the contribution 🥳 

Merging in; will make minor adjustments in a subsequent commit (minor text change and will move the filter closer to file search) 🙇‍♂️ 

Cheers 🌞

2026-06-18 21:12 UTC, merged