removed animation on clicking rescan
whyboris/Video-Hub-App pull request #848
Opened 2024-02-24 06:06 UTC by schandrasv

this PR fixes issue #844 

https://github.com/whyboris/Video-Hub-App/assets/61049388/bff5de8c-11c2-4c27-9bcd-b848c399f36f

2024-02-24 20:01 UTC, whyboris requested changes
I didn't test the code, but I'm pretty sure the animation will no longer play when the user _left clicks_ 😅 

The animation should work when left-clicking (as the app will perform the _rescan_ functionality) but right-clicking does not (and should not) perform the _rescan_ ✅

2024-02-25 01:39 UTC, schandrasv commented
added another commit to fix the issue

2024-02-25 13:40 UTC, whyboris commented
Thank you! I suspect this works great - will test and merge next time I'm doing some VHA coding (sometime during March); please let me know if you'd like it merged sooner 🙇‍♂️

2024-05-20 18:18 UTC, whyboris commented
My house projects are taking so much longer than coding 😅 
Refactoring an app can be as little as a few days of work; rebuilding a kitchen can take as long as many months 😓
I'll try to get to coding in the coming months, though I'm still deep in house work 🙇‍♂️
Thank you for your patience -- I intend to merge this PR this year; surely before any new VHA release occurs 🤝

2026-06-19 17:13 UTC, whyboris commented
Thank you @schandrasv for the improvement! Sorry took a while to release; now that `3.3.0` is coming, this code will be in it 🚀

2026-06-19 17:13 UTC, merged